[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc_print = { version = "0.1.0", path = "libc_print-dynamic", package = "libc_print-dynamic" }
